### ISSUE TITLE
extra byte in pck_cert_chain data

### ISSUE THREAD

**Issue by mythi** [google/go-tdx-guest#34]
For some reason I'm seeing: `pck_cert_chain:"...\n-----END CERTIFICATE-----\n\x00"`. The size seems OK since all other validation passes except when parsing the certificates for verification.

I'm seeing `len(rem) == 1` with:
https://github.com/google/go-tdx-guest/blob/efcfb93790684f5c8730ff77876d3d1932f7e35f/verify/verify.go#L641-L643

so this one helps
```
-       if root == nil || len(rem) != 0 || root.Type != certificateType {
+       if root == nil || root.Type != certificateType {  
```

with `echo -e <the pck_cert_chain content in parenthesis> | wc` suggests that `\x00` is indeed extra because wc gives size+1 bytes. 

Go 1.21.x
Command: `../attest/attest | ./check`
Linux 6.7 from Ubuntu mainline PPA

**Comment by jrjatin** [comment]
Can you please verify if the anticipated size aligns with the length of pckCertChain? Does this size include the trailing zero byte?
 https://github.com/google/go-tdx-guest/blob/main/abi/abi.go#L563C2-L565C3 
 
 
The existing code assumes that any trailing zeroes (following pckCertData) are included within extraBytes.
 https://github.com/google/go-tdx-guest/blob/main/proto/tdx.proto#L37

**Comment by mythi** [comment]
> Can you please verify if the anticipated size aligns with the length of pckCertChain? Does this size include the trailing zero byte?

Printing out `chain.GetPckCertChain()[chain.GetSize()-1]` seems to give me the zero byte (-2 gives \n)

**Comment by daniel-weisse** [comment]
I have the same issue.
Parsing my raw report with `abi.QuoteToProto()` returns a `tdx.QuoteV4` object where the reported size and length of the certificate field are equal.

E.g.
```Go
pbQuote, _ := abi.QuoteToProto(attRaw)
quote := pbQuote.(*tdx.QuoteV4)
certChainData := quote.GetSignedData().GetCertificationData().GetQeReportCertificationData().GetPckCertificateChainData()
fmt.Println(certChainData.Size) // prints 3682
fmt.Println(certChainData.GetPckCertChain()) // prints 3682
```

Though this is not explicitly defined in the TDX spec, I think the certificate chain is supposed to be terminated by a null byte.
At least that was the case when I tested quoting in the Intel Dev cloud, and is currently the case for TDX instances on Azure.

This is not supported by this library however, which has a hard requirement on no extra data trailing behind the root certificate:https://github.com/google/go-tdx-guest/blob/efcfb93790684f5c8730ff77876d3d1932f7e35f/verify/verify.go#L641-L644

Changing the condition to check if any trailing byte is `0x00` would fix the issue:
```Go
	root, rem := pem.Decode(rem)
	if root == nil || (len(rem) != 0 && !bytes.Equal(rem, []byte{0x00})) || root.Type != certificateType {
		return nil, ErrPCKCertChainInvalid
	}
```

**Comment by jrjatin** [comment]
Thanks for bringing this issue and for your suggestions. We are working on it and will soon update the changes.

**Comment by jrjatin** [comment]
https://github.com/google/go-tdx-guest/pull/36 This should fix the issue

**Comment by mythi** [comment]
I can confirm the fix works here, thanks!
