### ISSUE TITLE
stat /sys/kernel/config/tsm/rtmrs: no such file or directory

### ISSUE THREAD

**Issue by privacywill** [google/go-tdx-guest#54]
The guest kernel I used hasn't merged the tsm rtmr [patches](https://patchew.org/linux/20240114223532.290550-1-sameo@rivosinc.com/20240114223532.290550-5-sameo@rivosinc.com/). 

So the directorty `/sys/kernel/config/tsm/rtmrs` doesn't exist in my guest which results in error when `ExtendDigest` to RTMR. 

So how can I extend to RTMR in this situation?

**Comment by privacywill** [comment]
https://github.com/google/go-tdx-guest/compare/main...privacywill:go-tdx-guest:extend-rtmr

I added some codes to support extending rtmr. But it failed with error `inappropriate ioctl for device`.
Does any one knows the reason? Thanks!

**Comment by qinkunbao** [comment]
Hi,

The current RTMR implementation in go-tdx-guest is based on the following patch. 

https://lore.kernel.org/linux-coco/20240128212532.2754325-1-sameo@rivosinc.com/

Unfortunately the patch has not been merged into the upstream kernel. If you would like to extend the RTMR values from the user space, you need to back port the following patches into the kernel.
https://github.com/intel/tdx/commits/guest-rtmr/ (last six commits)

Once you have backported the patch, you can use the following functions to extend the rtmr values.
https://github.com/google/go-tdx-guest/blob/main/rtmr/extend.go#L66

> https://github.com/google/go-tdx-guest/compare/main...privacywill:go-tdx-guest:extend-rtmr
To my knowledge, there isn't an ioctl interface that enables userspace extension of rtmr values. Any upcoming attestation-related patches will be built upon configfs-tsm.

Cedric Xing (Intel) published a version of the RTMR patch series.
https://lore.kernel.org/linux-coco/20241031-tsm-rtmr-v2-0-1a6762795911@intel.com/
We will update the go-tdx-guest once the above patch series has been upstreamed.

**Comment by privacywill** [comment]
> To my knowledge, there isn't an ioctl interface that enables userspace extension of rtmr values. Any upcoming attestation-related patches will be built upon configfs-tsm.

hi thanks for reply. 

I followed the codes in DCAP repo. As the code shows, it utilizes ioctl to extend the RTMR. I am not sure how that works.

https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/aa239d25a437a28f3f4de92c38f5b6809faac842/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L945

**Comment by qinkunbao** [comment]
> https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/aa239d25a437a28f3f4de92c38f5b6809faac842/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L945

The DCAP library was based on Intel's MVP kernel. The Intel's MVP kernel have many patches that are not upstreamed or public.

**Comment by privacywill** [comment]
https://github.com/google/go-tdx-guest/blob/097ee70d08434930049a72268ab0e1eca4e45152/client/linuxabi/linux_abi.go#L42

Do you know why the ioctl command `IocTdxGetQuote ` is  composed of`(0x2 << iocNrshift)`? And it's value is `3222295554`

While the ioctl command in DCAP library is`#define TDX_CMD_GET_QUOTE _IOWR('T', 4, struct tdx_quote_req)`. And it's value is `3222295556`
 https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/aa239d25a437a28f3f4de92c38f5b6809faac842/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L72

Is this a bug for `go-tdx-guest?` Or any reason that I don't know.

**Comment by qinkunbao** [comment]
Ok, please forget about the ioctl interface. There are many versions of the ioctl patches. DCAP and go-tdx-guest may be based on different versions.

**Comment by kws1207** [comment]
Hi, are there any updates on this issue?

**Comment by pavgup** [comment]
@privacywill this was closed as `completed`, does that mean this have been upstreamed?
